-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."softcartDimDate"
(
    dateid integer NOT NULL,
    date date NOT NULL,
    day_of_week integer NOT NULL,
    day_of_month integer NOT NULL,
    weekday_name character varying(10) NOT NULL,
    month integer NOT NULL,
    month_name character varying(10) NOT NULL,
    quarter integer NOT NULL,
    year integer NOT NULL,
    is_weekend boolean,
    is_holiday boolean,
    PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCategory"
(
    category_id integer NOT NULL,
    category_name character varying(255) NOT NULL,
    category_description text NOT NULL,
    department_name character varying(255) NOT NULL,
    PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public."softcartDimItem"
(
    item_id integer NOT NULL,
    item_name character varying(255) NOT NULL,
    item_description text,
    PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCountry"
(
    country_id integer NOT NULL,
    country_name character varying(255) NOT NULL,
    region character varying(255),
    PRIMARY KEY (country_id)
);

CREATE TABLE IF NOT EXISTS public."softcartFactSales"
(
    sale_id integer NOT NULL,
    date_id integer,
    item_id integer,
    country_id integer,
    category_id integer,
    units_sold integer,
    revenue money,
    PRIMARY KEY (sale_id)
);

ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (date_id)
    REFERENCES public."softcartDimDate" (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (item_id)
    REFERENCES public."softcartDimItem" (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (country_id)
    REFERENCES public."softcartDimCountry" (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (category_id)
    REFERENCES public."softcartDimCategory" (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;